//
// Generated file, do not edit! Created by nedtool 4.6 from messages/RFID_Message.msg.
//

#ifndef _RFID_MESSAGE_M_H_
#define _RFID_MESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/RFID_Message.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet RFID_Message
 * {
 *     int tag_id;
 * }
 * </pre>
 */
class RFID_Message : public ::cPacket
{
  protected:
    int tag_id_var;

  private:
    void copy(const RFID_Message& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RFID_Message&);

  public:
    RFID_Message(const char *name=NULL, int kind=0);
    RFID_Message(const RFID_Message& other);
    virtual ~RFID_Message();
    RFID_Message& operator=(const RFID_Message& other);
    virtual RFID_Message *dup() const {return new RFID_Message(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getTag_id() const;
    virtual void setTag_id(int tag_id);
};

inline void doPacking(cCommBuffer *b, RFID_Message& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RFID_Message& obj) {obj.parsimUnpack(b);}


#endif // ifndef _RFID_MESSAGE_M_H_

